package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.provider.ContactsContract;

/**
 * Entity mapped to table "WIFI_LOG".
 */
public class WifiLog {

    private Long id;
    private String name;
    private long time;
    private String BSSID;
    private String data;

    public WifiLog() {
    }

    public WifiLog(Long id) {
        this.id = id;
    }

    public WifiLog(Long id, String name, long time, String BSSID, String data) {
        this.id = id;
        this.name = name;
        this.time = time;
        this.BSSID = BSSID;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public String getBSSID() {
        return BSSID;
    }

    public void setBSSID(String BSSID) {
        this.BSSID = BSSID;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}
